import os

import streamlit as st
import datetime
import requests
import sys
from logger.logging import get_logger

logger = get_logger(__name__)


BASE_URL = "http://localhost:8000"  # Replace with your FastAPI server URL

st.set_page_config(
    page_title="Travel Planner Agentic App",
    page_icon="🌏",  # You can use an emoji or a URL to an image
    layout="centered",
    initial_sidebar_state="expanded"
)

st.title("🌏 Travel Planner Agentic App")

# Initialize chat history in session state
if "messages" not in st.session_state:
    st.session_state.messages = []


st.header("How can I assist you with your travel plans today? Let's make your travel planning effortless and enjoyable! 🌟")


with st.form(key="query_form", clear_on_submit=True):
    input_user = st.text_area(
        "Enter your travel query:",
        placeholder="Ask me anything about your travel plans...",
        height=250
    )
    button_submit = st.form_submit_button("Send")


if button_submit and input_user.strip():
    try:
        # Show user a message
        # Show thinking message while waiting for the response
        with st.spinner("AI is thinking..."):
            payload = {"query": input_user}  # ✅ Matches FastAPI schema
            logger.debug(f"Payload: {payload}")
            response = requests.post(f"{BASE_URL}/query", json=payload)
            
        if response.status_code == 200:
            res_json = response.json()
            answer = res_json.get("answer").get("content") or res_json.get("response").get("content") or "No answer received."
            markdown_message = f"""
            # 🌏 AI Travel Planner

            **Generated:** {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
            **Created by:** RB's Travel Agent  

            ---

            {answer}

            ---

            *This travel plan was generated by the AI Travel Planner. Please verify the information especially prices before making any travel arrangements.*
            """
            st.markdown(markdown_message)
        else:
            st.error(f"Travel Agent failed to respond (Status {response.status_code}): {response.text}")

    except Exception as e:
        st.error(f"Error occurred while processing the request: {e}")